# version: "3.9"
# services:
#   app:
#     build: .
#     ports:
#       - "3000:3000"
#     environment:
#       - PORT=3000
#     command: npm start

version: "3.8"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    volumes:
      - .:/app
    command: npm start
